public class PAPDFController {
/*    
    public Product_Analysis__c PARecord { get; set; }
    //public String AccountName { get; set; }
        
    public PAPDFController() {
        String paId = ApexPages.currentPage().getParameters().get('id');
        system.debug('paId '+ paId );
        system.debug('ApexPages-currentPage-getParameters '+ ApexPages.currentPage().getParameters() );
        PARecord = [SELECT Id,
                    account__c, 
                    account__r.Name, 
                    Current_Bottom_Load_Force__c, 
                    Current_Estimated_Annual_Cost__c,
                    Current_Film_Thickness_ga__c, 
                    Current_Film_Width_in__c, 
                    Current_Item__c, 
                    Current_Manufacturer__c,
                    Current_Middle_Load_Force__c, 
                    Current_Roll_Length_ft__c, 
                    Current_Roll_Price__c, 
                    Current_Rotations__c, 
                    Current_Top_Load_Force__c, 
                    Current_Total_Stretch__c,
                    Current_Weight_oz__c,
                    Equipment_Type__c,
                    Manufacturer_Model__c,
                    Pallet_Height_in__c,
                    Pallet_Length_in__c,
                    Pallets_Per_Year__c, 
                    Pallet_Type__c,
                    Pallet_Weight_lbs__c,
                    Pallet_Width_in__c,
                    Proposed_Annual_Savings__c,
                    Proposed_Bottom_Load_Force__c,
                    Proposed_Estimated_Annual_Cost__c,
                    Proposed_Film_Thickness_ga__c,
                    Proposed_Film_Width_in__c,
                    Proposed_Item__c,
                    Proposed_Middle_Load_Force__c,
                    Proposed_Percent_Savings__c,
                    Proposed_Roll_Length_ft__c,
                    Proposed_Roll_Price__c,
                    Proposed_Rotations__c,
                    Proposed_Top_Load_Force__c,
                    Proposed_Total_Stretch__c,
                    Proposed_Weight_oz__c,
                    Serial_Number__c,
                    Waste_Stream_Pounds_Reduction__c,
                    Plastic_Straws_Saved__c,
                    Plastic_Bags_Saved__c,
                    Plastic_Bottles_Saved__c,
                    Personal_Vehicle_Emissions__c,
                    Barrels_of_Oil__c,
                    Homes_Powered__c,
                    Film__c,
                    Pallets__c,
                    Truckloads__c,
                    BarrelInd__c,
                    CarInd__c,
                    CoreInd__c,
                    HomeInd__c,
                    PalletInd__c,
                    PlasticBagInd__c,
                    PlasticBottleInd__c,
                    PlasticStrawInd__c,
                    TruckInd__c
                    FROM Product_Analysis__c
                    WHERE Id = :paId LIMIT 1];
     
        system.debug('The pdf page:'+ PARecord);
    }
 */  
}